# see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
name: Publish Package at Github Registry

on:
  push:
    tags:
      - 'v*'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm i

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: "chore: Bum up packages version to publish"
          commit: "chore: Bump up packages version to publish"
          version: pnpm changeset:version
          publish: pnpm changeset:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github-builds
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
