# see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
name: Publish Package at Github Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - /^release/.*$/
      - /^feature/.*$/
    types: [opened, synchronize, reopened]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm i

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: "chore: Bum up packages version to publish"
          commit: "chore: Bump up packages version to publish"
          version: npm run changeset:version
          publish: npm run changeset:publish
        env:
          GITHUB_TOKEN: ${{secrets.SEOLHUN_GITHUB_TOKEN}}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github-builds
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
