name: Release Drafter

on:
  push:
    tags:
      - 'main'

concurrency: release-drafter

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          NODE_AUTH_TOKEN: ${{secrets.SEOLHUN_GITHUB_TOKEN}}
        with:
          config-name: release-drafter.yml
